title: Evan Skinner for County Commissioner
description: A campaign for responsible leadership and community growth.
baseurl: "/mysite"
url: "https://cicada3300.github.io"

markdown: kramdown
theme: null